<?php

// تأكد إن الجلسة شغالة
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$lang = $_SESSION['lang'] ?? 'en';

$translations = [

    'en' => [
        'title' => 'Alibaba',

        'desc' => 'Alibaba is a modern neon-powered food experience designed for speed and simplicity. We bring together fast ordering, smooth navigation, and a futuristic dining vibe that fits today’s digital lifestyle. Explore a wide variety of meals, enjoy a seamless ordering system, and experience food in a new cyber-inspired way.',

        'login' => 'Login Now',

        // login page
        'login_title' => 'Login / Register',
        'signin_text' => 'Already Have an Account?',
        'signup_text' => "Don’t Have an Account?",
        'signin_btn' => 'Sign in',
        'signup_btn' => 'Sign up',

        'signin_header' => 'Sign In',
        'signup_header' => 'Sign Up',

        'email' => 'Email',
        'password' => 'Password',
        'confirm_password' => 'Confirm Password',
        'username' => 'Username',
        'age' => 'Age',

        'male' => 'Male',
        'female' => 'Female',

        'login_btn' => 'Login',
        'signup_btn_submit' => 'Sign Up','products_title' => 'Products Page',
'home' => 'Home',
'menu' => 'Menu',
'about' => 'About',
'contact' => 'Contact',
'my_orders' => 'My Orders',
'logout' => 'Logout',

'search' => 'Search',
'price' => 'Price',
'add_to_cart' => 'Add To Cart',
'out_of_stock' => 'Out Of Stock',
'choose_flavor' => 'Choose Flavor',

'your_cart' => 'Your Cart',
'total' => 'Total',
'close' => 'Close',
'clear_all' => 'Clear All',
'confirm_order' => 'Confirm Order (QR Table)',
'takeaway' => 'Takeaway',

'no_products' => 'No products available',
'about_title' => 'About Us',
'about_us' => 'About Us',
'who_we_are' => 'Who We Are',
'about_intro_1' => 'Welcome to our cafeteria system...',
'about_intro_2' => 'Our goal is to create a modern environment...',
'our_vision' => 'Our Vision',
'vision_text' => 'To build a smart and organized ordering system...',
'our_team' => 'Our Team',
'team_text' => 'This project was developed by a team of eight students...',
'back_menu' => 'Back Menu',
'contact_title' => 'Contact Us',
'first_name' => 'First Name',
'last_name' => 'Last Name',
'message_here' => 'Type Your Message Here:',
'message_placeholder' => 'Your message...',
'send' => 'Send',
'follow_us' => 'Follow Us',
'sent_success' => 'Message sent successfully!',
'sent_error' => 'Error sending message.',
'my_orders_title' => 'My Orders',
'back_to_menu' => 'Back to Menu',
'no_orders' => 'You have no orders yet.',
'reorder_confirm' => 'Do you want to order the same items again?',
'order_success' => 'Order placed successfully!',
'order_failed' => 'Failed to reorder',
'completed' => 'Completed',
'pending' => 'Pending',
'cancelled' => 'Cancelled',
'order_again' => 'Order Again',
'add_user' => 'Add User',
    'edit_user' => 'Edit User',
    'delete' => 'Delete',
    'edit' => 'Edit',
    'name' => 'Name',
    'role' => 'Role',
    'action' => 'Action',
    'add_table' => 'Add Table',
    'add_product' => 'Add Product',
    'flavors' => 'Flavors',
    'confirm_delete_user' => 'Are you sure to delete this user?',
    'confirm_delete_table' => 'Are you sure to delete this table?',
    'confirm_delete_product' => 'Are you sure to delete this product?',
    'no_messages' => 'No messages yet...',
    'description' => 'Description',
'stock_quantity' => 'Stock Quantity',
'category_id' => 'Category ID',
'image' => 'Image',
'save' => 'Save',
'table_number' => 'Table Number',
'status' => 'Status',
'flavor_name' => 'Flavor Name',
'stock' => 'Stock',
'admin' => 'Admin',
'admin_dashboard' => 'Admin Dashboard',
'orders' => 'Orders',
'tables' => 'Tables',
'products' => 'Products',
'users' => 'Users',
'messages' => 'Messages',
"phone"=> "Phone Number",
"analytics"=> "Analytics",
'export_daily_excel' => 'Export Daily Excel',
'export_monthly_excel' => 'Export Monthly Excel',
'export_yearly_excel' => 'Export Yearly Excel',

'export_daily_pdf' => 'Export Daily PDF',
'export_monthly_pdf' => 'Export Monthly PDF',
'export_yearly_pdf' => 'Export Yearly PDF',
'export_excel' => 'Export Excel',
'export_pdf' => 'Export PDF',
'from' => 'From',
'to' => 'To',
'backup_system' => 'Backup System',
'daily_backup' => 'Daily Backup',
'monthly_backup' => 'Monthly Backup',
'yearly_backup' => 'Yearly Backup',


    ],

    'ar' => [
        'title' => 'علي بابا',

        'desc' => 'علي بابا هي تجربة طعام حديثة تعمل بالنيون ومصممة للسرعة والبساطة. نحن نجمع بين الطلب السريع والتنقل السلس وأجواء تناول الطعام المستقبلية التي تناسب نمط الحياة الرقمي اليوم.',

        'login' => 'تسجيل الدخول',

        // login page
        'login_title' => 'تسجيل الدخول / إنشاء حساب',
        'signin_text' => 'عندك حساب بالفعل؟',
        'signup_text' => 'مش عندك حساب؟',
        'signin_btn' => 'تسجيل الدخول',
        'signup_btn' => 'إنشاء حساب',

        'signin_header' => 'تسجيل الدخول',
        'signup_header' => 'إنشاء حساب',

        'email' => 'البريد الإلكتروني',
        'password' => 'كلمة المرور',
        'confirm_password' => 'تأكيد كلمة المرور',
        'username' => 'اسم المستخدم',
        'age' => 'العمر',

        'male' => 'ذكر',
        'female' => 'أنثى',

        'login_btn' => 'دخول',
        'signup_btn_submit' => 'تسجيل',
        'products_title' => 'صفحة المنتجات',
'home' => 'الرئيسية',
'menu' => 'المنيو',
'about' => 'عن الموقع',
'contact' => 'تواصل',
'my_orders' => 'طلباتي',
'logout' => 'تسجيل خروج',

'search' => 'بحث',
'price' => 'السعر',
'add_to_cart' => 'أضف للسلة',
'out_of_stock' => 'غير متوفر',
'choose_flavor' => 'اختر النكهة',

'your_cart' => 'سلة الطلبات',
'total' => 'الإجمالي',
'close' => 'إغلاق',
'clear_all' => 'مسح الكل',
'confirm_order' => 'تأكيد الطلب (QR)',
'takeaway' => 'تيك أواي',

'no_products' => 'لا توجد منتجات',
'about_title' => 'من نحن',
'about_us' => 'من نحن',
'who_we_are' => 'من نحن',
'about_intro_1' => 'مرحبًا بك في نظام الكافيتريا...',
'about_intro_2' => 'هدفنا هو إنشاء نظام حديث...',
'our_vision' => 'رؤيتنا',
'vision_text' => 'بناء نظام ذكي ومنظم...',
'our_team' => 'فريق العمل',
'team_text' => 'تم تطوير هذا المشروع بواسطة 8 طلاب...',
'back_menu' => 'رجوع للمنيو',
'contact_title' => 'تواصل معنا',
'first_name' => 'الاسم الأول',
'last_name' => 'الاسم الأخير',
'message_here' => 'اكتب رسالتك هنا:',
'message_placeholder' => 'رسالتك...',
'send' => 'إرسال',
'follow_us' => 'تابعنا',
'sent_success' => 'تم إرسال الرسالة بنجاح!',
'sent_error' => 'حدث خطأ أثناء الإرسال.',
'my_orders_title' => 'طلباتي',
'back_to_menu' => 'رجوع للمنيو',
'no_orders' => 'لا توجد طلبات حتى الآن',
'reorder_confirm' => 'هل تريد طلب نفس العناصر مرة أخرى؟',
'order_success' => 'تم إنشاء الطلب بنجاح!',
'order_failed' => 'فشل إعادة الطلب',
'completed' => 'مكتمل',
'pending' => 'قيد الانتظار',
'cancelled' => 'ملغي',
'order_again' => 'اطلب مرة أخرى',
 'add_user' => 'إضافة مستخدم',
    'edit_user' => 'تعديل مستخدم',
    'delete' => 'حذف',
    'edit' => 'تعديل',
    'name' => 'الاسم',
    'role' => 'الدور',
    'action' => 'الإجراء',
    'add_table' => 'إضافة طاولة',
    'add_product' => 'إضافة منتج',
    'flavors' => 'النكهات',
    'confirm_delete_user' => 'هل أنت متأكد من حذف المستخدم؟',
    'confirm_delete_table' => 'هل أنت متأكد من حذف الطاولة؟',
    'confirm_delete_product' => 'هل أنت متأكد من حذف المنتج؟',
    'no_messages' => 'لا توجد رسائل',
    'description' => 'الوصف',
'stock_quantity' => 'كمية المخزون',
'category_id' => 'رقم القسم',
'image' => 'الصورة',
'save' => 'حفظ', 'تعديل مستخدم',
'table_number' => 'رقم الطاولة',
'status' => 'الحالة',
'flavor_name' => 'اسم النكهة',
'stock' => 'المخزون',
'admin' => 'الأدمن',
'admin_dashboard' => 'لوحة التحكم',
'orders' => 'الطلبات',
'tables' => 'الطاولات',
'products' => 'المنتجات',
'users' => 'المستخدمين',
'messages' => 'الرسائل',
'phone'=> "رقم الهاتف",
'analytics'=> "التحليلات",
'export_daily_excel' => 'تصدير يومي Excel',
'export_monthly_excel' => 'تصدير شهري Excel',
'export_yearly_excel' => 'تصدير سنوي Excel',

'export_daily_pdf' => 'تصدير يومي PDF',
'export_monthly_pdf' => 'تصدير شهري PDF',
'export_yearly_pdf' => 'تصدير سنوي PDF',
'export_excel' => 'تصدير Excel',
'export_pdf' => 'تصدير PDF',
'from' => 'من',
'to' => 'إلى',
'backup_system' => 'نظام النسخ الاحتياطي',
'daily_backup' => 'نسخة يومية',
'monthly_backup' => 'نسخة شهرية',
'yearly_backup' => 'نسخة سنوية',
    ]

];

// helper function سهلة الاستخدام
function t($key) {
    global $translations;

    $lang = $_SESSION['lang'] ?? 'en';

    return $translations[$lang][$key] ?? $key;
}